---
-  name: install nginx in web server
   hosts: web
   become: true
   tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true
    - name: ensures copy of index.html
      copy:
        src: /home/ubuntu/2025ansible/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp

- name: install nginx in db server
  hosts: db
  become: true
  tasks:
    - name: install nginx in db server
      apt:
        name: nginx
        state: present
    - name: ensure nginx is running in db server
      service:
        name: nginx
        state: started
        enabled: true
    - name: ensures copy of index1.html in db server
      copy:
        src: /home/ubuntu/2025ansible/index1.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        force: yes
    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp