---
- name: install nginx in web servers
  hosts: web
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: true
    - name: create directory for site1
      file:
        path: /var/www/html/site1
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: create directory for site2
      file:
        path: /var/www/html/site2
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: ensures copy of index.html
      copy:
        src: /home/ubuntu/2025ansible/files/site1/index.html
        dest: /var/www/html/site1/index.html
    - name: ensures copy of index.html for site2
      copy:
        src: /home/ubuntu/2025ansible/files/site2/index.html
        dest: /var/www/html/site2/index.html
    - name: remove default nginx index.html
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: copy custom nginx conf for /var/www/html/site1
      copy:
        src: /home/ubuntu/2025ansible/files/site1.conf
        dest: /etc/nginx/sites-available/site1.conf
    - name: copy custom nginx conf for /var/www/html/site2
      copy:
        src: /home/ubuntu/2025ansible/files/site2.conf
        dest: /etc/nginx/sites-available/site2.conf
    - name: enable site1 configuration
      file:
        src: /etc/nginx/sites-available/site1.conf
        dest: /etc/nginx/sites-enabled/site1.conf
        state: link
    - name: enable site2 configuration
      file:
        src: /etc/nginx/sites-available/site2.conf
        dest: /etc/nginx/sites-enabled/site2.conf
        state: link
    - name: restart nginx to apply changes
      service:
        name: nginx
        state: restarted
        enabled: true